export const LOADING_COUNTRIES = 'LOADING_COUNTRIES';
export const COUNTRIES_LOADED = 'COUNTRIES_LOADED';
export const COUNTRIES_ERROR = 'COUNTRIES_ERROR';
export const SET_CONTINENT_FILTER = 'SET_CONTINENT_FILTER';
